on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: docker
    steps:
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - shell: bash
        run: |
          git clone -b main https://placeholder:${{ secrets.PAGES_TOKEN }}@kitsunes.dev/LunaFox/docs-2 /tmp/docs
          git clone -b pages https://placeholder:${{ secrets.PAGES_TOKEN }}@kitsunes.dev/LunaFox/docs-2 /tmp/docs-dist

          git -C /tmp/docs config user.email "fox@trans.fish"
          git -C /tmp/docs config user.name "LunaFox-CI"

          git -C /tmp/docs-dist config user.email "fox@trans.fish"
          git -C /tmp/docs-dist config user.name "LunaFox-CI"

          cd /tmp/docs
          bun install --frozen-lockfile
          bun --bun run build
          cp -r docs/.vitepress/dist /tmp/dist

          cd /tmp/docs-dist
          cp -r /tmp/dist/* .
          git add .

          git diff-index --quiet HEAD || git commit -m 'ci: Deploy' -a
          git push --force origin pages
