on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: docker
    steps:
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - shell: bash
        run: |
          git clone https://placeholder:${{ secrets.PAGES_TOKEN }}@kitsunes.dev/LunaFox/docs-2 /tmp/docs

          cd /tmp/docs
          git config user.email "fox@trans.fish"; git config user.name "LunaFox-CI"

          mkdir /tmp/docs-dist
          cp -r /tmp/docs/.git /tmp/docs-dist/.git
          git -C /tmp/docs-dist switch -C pages

          bun install --frozen-lockfile
          bun --bun run build
          cp -r docs/.vitepress/dist /tmp/dist

          cd /tmp/docs-dist
          cp -r /tmp/dist/* .
          git add .

          git diff-index --quiet HEAD || git commit -m 'ci: Deploy' -a
          git push --force origin pages
